/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Weapon.def
	public class EntityBaseEntityCall_WeaponBase : EntityCall
	{

		public EntityBaseEntityCall_WeaponBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

	}

	public class EntityCellEntityCall_WeaponBase : EntityCall
	{

		public EntityCellEntityCall_WeaponBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void setCruiseSpeed(UInt16 arg1)
		{
			Bundle pBundle = newCall("setCruiseSpeed", 0);
			if(pBundle == null)
				return;

			bundle.writeUint16(arg1);
			sendCall(null);
		}

	}
	}
