/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAccountModule = new ScriptModule("Account");
			EntityDef.moduledefs["Account"] = pAccountModule;
			EntityDef.idmoduledefs[1] = pAccountModule;

			Property pAccount_position = new Property();
			pAccount_position.name = "position";
			pAccount_position.properUtype = 40000;
			pAccount_position.properFlags = 4;
			pAccount_position.aliasID = 1;
			Vector3 Account_position_defval = new Vector3();
			pAccount_position.defaultVal = Account_position_defval;
			pAccountModule.propertys["position"] = pAccount_position; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_position.aliasID] = pAccount_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(position / 40000).");

			Property pAccount_direction = new Property();
			pAccount_direction.name = "direction";
			pAccount_direction.properUtype = 40001;
			pAccount_direction.properFlags = 4;
			pAccount_direction.aliasID = 2;
			Vector3 Account_direction_defval = new Vector3();
			pAccount_direction.defaultVal = Account_direction_defval;
			pAccountModule.propertys["direction"] = pAccount_direction; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_direction.aliasID] = pAccount_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(direction / 40001).");

			Property pAccount_spaceID = new Property();
			pAccount_spaceID.name = "spaceID";
			pAccount_spaceID.properUtype = 40002;
			pAccount_spaceID.properFlags = 16;
			pAccount_spaceID.aliasID = 3;
			UInt32 Account_spaceID_defval;
			UInt32.TryParse("", out Account_spaceID_defval);
			pAccount_spaceID.defaultVal = Account_spaceID_defval;
			pAccountModule.propertys["spaceID"] = pAccount_spaceID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_spaceID.aliasID] = pAccount_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(spaceID / 40002).");

			Property pAccount_lastSelCharacter = new Property();
			pAccount_lastSelCharacter.name = "lastSelCharacter";
			pAccount_lastSelCharacter.properUtype = 2;
			pAccount_lastSelCharacter.properFlags = 32;
			pAccount_lastSelCharacter.aliasID = 4;
			UInt64 Account_lastSelCharacter_defval;
			UInt64.TryParse("0", out Account_lastSelCharacter_defval);
			pAccount_lastSelCharacter.defaultVal = Account_lastSelCharacter_defval;
			pAccountModule.propertys["lastSelCharacter"] = pAccount_lastSelCharacter; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_lastSelCharacter.aliasID] = pAccount_lastSelCharacter;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(lastSelCharacter / 2).");

			List<DATATYPE_BASE> pAccount_onCreateAvatarResult_args = new List<DATATYPE_BASE>();
			pAccount_onCreateAvatarResult_args.Add(EntityDef.id2datatypes[2]);
			pAccount_onCreateAvatarResult_args.Add(EntityDef.id2datatypes[26]);

			Method pAccount_onCreateAvatarResult = new Method();
			pAccount_onCreateAvatarResult.name = "onCreateAvatarResult";
			pAccount_onCreateAvatarResult.methodUtype = 10005;
			pAccount_onCreateAvatarResult.aliasID = 1;
			pAccount_onCreateAvatarResult.args = pAccount_onCreateAvatarResult_args;

			pAccountModule.methods["onCreateAvatarResult"] = pAccount_onCreateAvatarResult; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onCreateAvatarResult.aliasID] = pAccount_onCreateAvatarResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onCreateAvatarResult / 10005).");

			List<DATATYPE_BASE> pAccount_onRemoveAvatar_args = new List<DATATYPE_BASE>();
			pAccount_onRemoveAvatar_args.Add(EntityDef.id2datatypes[5]);

			Method pAccount_onRemoveAvatar = new Method();
			pAccount_onRemoveAvatar.name = "onRemoveAvatar";
			pAccount_onRemoveAvatar.methodUtype = 3;
			pAccount_onRemoveAvatar.aliasID = 2;
			pAccount_onRemoveAvatar.args = pAccount_onRemoveAvatar_args;

			pAccountModule.methods["onRemoveAvatar"] = pAccount_onRemoveAvatar; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onRemoveAvatar.aliasID] = pAccount_onRemoveAvatar;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onRemoveAvatar / 3).");

			List<DATATYPE_BASE> pAccount_onReqAvatarList_args = new List<DATATYPE_BASE>();
			pAccount_onReqAvatarList_args.Add(EntityDef.id2datatypes[27]);

			Method pAccount_onReqAvatarList = new Method();
			pAccount_onReqAvatarList.name = "onReqAvatarList";
			pAccount_onReqAvatarList.methodUtype = 10003;
			pAccount_onReqAvatarList.aliasID = 3;
			pAccount_onReqAvatarList.args = pAccount_onReqAvatarList_args;

			pAccountModule.methods["onReqAvatarList"] = pAccount_onReqAvatarList; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_onReqAvatarList.aliasID] = pAccount_onReqAvatarList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(onReqAvatarList / 10003).");

			List<DATATYPE_BASE> pAccount_reqAvatarList_args = new List<DATATYPE_BASE>();

			Method pAccount_reqAvatarList = new Method();
			pAccount_reqAvatarList.name = "reqAvatarList";
			pAccount_reqAvatarList.methodUtype = 10001;
			pAccount_reqAvatarList.aliasID = -1;
			pAccount_reqAvatarList.args = pAccount_reqAvatarList_args;

			pAccountModule.methods["reqAvatarList"] = pAccount_reqAvatarList; 
			pAccountModule.base_methods["reqAvatarList"] = pAccount_reqAvatarList;

			pAccountModule.idbase_methods[pAccount_reqAvatarList.methodUtype] = pAccount_reqAvatarList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqAvatarList / 10001).");

			List<DATATYPE_BASE> pAccount_reqRemoveAvatar_args = new List<DATATYPE_BASE>();
			pAccount_reqRemoveAvatar_args.Add(EntityDef.id2datatypes[12]);

			Method pAccount_reqRemoveAvatar = new Method();
			pAccount_reqRemoveAvatar.name = "reqRemoveAvatar";
			pAccount_reqRemoveAvatar.methodUtype = 1;
			pAccount_reqRemoveAvatar.aliasID = -1;
			pAccount_reqRemoveAvatar.args = pAccount_reqRemoveAvatar_args;

			pAccountModule.methods["reqRemoveAvatar"] = pAccount_reqRemoveAvatar; 
			pAccountModule.base_methods["reqRemoveAvatar"] = pAccount_reqRemoveAvatar;

			pAccountModule.idbase_methods[pAccount_reqRemoveAvatar.methodUtype] = pAccount_reqRemoveAvatar;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqRemoveAvatar / 1).");

			List<DATATYPE_BASE> pAccount_reqRemoveAvatarDBID_args = new List<DATATYPE_BASE>();
			pAccount_reqRemoveAvatarDBID_args.Add(EntityDef.id2datatypes[5]);

			Method pAccount_reqRemoveAvatarDBID = new Method();
			pAccount_reqRemoveAvatarDBID.name = "reqRemoveAvatarDBID";
			pAccount_reqRemoveAvatarDBID.methodUtype = 2;
			pAccount_reqRemoveAvatarDBID.aliasID = -1;
			pAccount_reqRemoveAvatarDBID.args = pAccount_reqRemoveAvatarDBID_args;

			pAccountModule.methods["reqRemoveAvatarDBID"] = pAccount_reqRemoveAvatarDBID; 
			pAccountModule.base_methods["reqRemoveAvatarDBID"] = pAccount_reqRemoveAvatarDBID;

			pAccountModule.idbase_methods[pAccount_reqRemoveAvatarDBID.methodUtype] = pAccount_reqRemoveAvatarDBID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqRemoveAvatarDBID / 2).");

			List<DATATYPE_BASE> pAccount_selectAvatarGame_args = new List<DATATYPE_BASE>();
			pAccount_selectAvatarGame_args.Add(EntityDef.id2datatypes[5]);

			Method pAccount_selectAvatarGame = new Method();
			pAccount_selectAvatarGame.name = "selectAvatarGame";
			pAccount_selectAvatarGame.methodUtype = 10004;
			pAccount_selectAvatarGame.aliasID = -1;
			pAccount_selectAvatarGame.args = pAccount_selectAvatarGame_args;

			pAccountModule.methods["selectAvatarGame"] = pAccount_selectAvatarGame; 
			pAccountModule.base_methods["selectAvatarGame"] = pAccount_selectAvatarGame;

			pAccountModule.idbase_methods[pAccount_selectAvatarGame.methodUtype] = pAccount_selectAvatarGame;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(selectAvatarGame / 10004).");

			ScriptModule pAvatarModule = new ScriptModule("Avatar");
			EntityDef.moduledefs["Avatar"] = pAvatarModule;
			EntityDef.idmoduledefs[4] = pAvatarModule;

			Property pAvatar_position = new Property();
			pAvatar_position.name = "position";
			pAvatar_position.properUtype = 40000;
			pAvatar_position.properFlags = 4;
			pAvatar_position.aliasID = 1;
			Vector3 Avatar_position_defval = new Vector3();
			pAvatar_position.defaultVal = Avatar_position_defval;
			pAvatarModule.propertys["position"] = pAvatar_position; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_position.aliasID] = pAvatar_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(position / 40000).");

			Property pAvatar_direction = new Property();
			pAvatar_direction.name = "direction";
			pAvatar_direction.properUtype = 40001;
			pAvatar_direction.properFlags = 4;
			pAvatar_direction.aliasID = 2;
			Vector3 Avatar_direction_defval = new Vector3();
			pAvatar_direction.defaultVal = Avatar_direction_defval;
			pAvatarModule.propertys["direction"] = pAvatar_direction; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_direction.aliasID] = pAvatar_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(direction / 40001).");

			Property pAvatar_spaceID = new Property();
			pAvatar_spaceID.name = "spaceID";
			pAvatar_spaceID.properUtype = 40002;
			pAvatar_spaceID.properFlags = 16;
			pAvatar_spaceID.aliasID = 3;
			UInt32 Avatar_spaceID_defval;
			UInt32.TryParse("", out Avatar_spaceID_defval);
			pAvatar_spaceID.defaultVal = Avatar_spaceID_defval;
			pAvatarModule.propertys["spaceID"] = pAvatar_spaceID; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_spaceID.aliasID] = pAvatar_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(spaceID / 40002).");

			Property pAvatar_Die_Count = new Property();
			pAvatar_Die_Count.name = "Die_Count";
			pAvatar_Die_Count.properUtype = 48005;
			pAvatar_Die_Count.properFlags = 16;
			pAvatar_Die_Count.aliasID = 4;
			UInt32 Avatar_Die_Count_defval;
			UInt32.TryParse("0", out Avatar_Die_Count_defval);
			pAvatar_Die_Count.defaultVal = Avatar_Die_Count_defval;
			pAvatarModule.propertys["Die_Count"] = pAvatar_Die_Count; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_Die_Count.aliasID] = pAvatar_Die_Count;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(Die_Count / 48005).");

			Property pAvatar_EXP = new Property();
			pAvatar_EXP.name = "EXP";
			pAvatar_EXP.properUtype = 47005;
			pAvatar_EXP.properFlags = 4;
			pAvatar_EXP.aliasID = 5;
			Int32 Avatar_EXP_defval;
			Int32.TryParse("0", out Avatar_EXP_defval);
			pAvatar_EXP.defaultVal = Avatar_EXP_defval;
			pAvatarModule.propertys["EXP"] = pAvatar_EXP; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_EXP.aliasID] = pAvatar_EXP;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(EXP / 47005).");

			Property pAvatar_EXP_Max = new Property();
			pAvatar_EXP_Max.name = "EXP_Max";
			pAvatar_EXP_Max.properUtype = 47006;
			pAvatar_EXP_Max.properFlags = 4;
			pAvatar_EXP_Max.aliasID = 6;
			Int32 Avatar_EXP_Max_defval;
			Int32.TryParse("0", out Avatar_EXP_Max_defval);
			pAvatar_EXP_Max.defaultVal = Avatar_EXP_Max_defval;
			pAvatarModule.propertys["EXP_Max"] = pAvatar_EXP_Max; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_EXP_Max.aliasID] = pAvatar_EXP_Max;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(EXP_Max / 47006).");

			Property pAvatar_HP = new Property();
			pAvatar_HP.name = "HP";
			pAvatar_HP.properUtype = 47001;
			pAvatar_HP.properFlags = 4;
			pAvatar_HP.aliasID = 7;
			Int32 Avatar_HP_defval;
			Int32.TryParse("0", out Avatar_HP_defval);
			pAvatar_HP.defaultVal = Avatar_HP_defval;
			pAvatarModule.propertys["HP"] = pAvatar_HP; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_HP.aliasID] = pAvatar_HP;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(HP / 47001).");

			Property pAvatar_HP_Max = new Property();
			pAvatar_HP_Max.name = "HP_Max";
			pAvatar_HP_Max.properUtype = 47002;
			pAvatar_HP_Max.properFlags = 4;
			pAvatar_HP_Max.aliasID = 8;
			Int32 Avatar_HP_Max_defval;
			Int32.TryParse("0", out Avatar_HP_Max_defval);
			pAvatar_HP_Max.defaultVal = Avatar_HP_Max_defval;
			pAvatarModule.propertys["HP_Max"] = pAvatar_HP_Max; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_HP_Max.aliasID] = pAvatar_HP_Max;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(HP_Max / 47002).");

			Property pAvatar_Kill_Count = new Property();
			pAvatar_Kill_Count.name = "Kill_Count";
			pAvatar_Kill_Count.properUtype = 48006;
			pAvatar_Kill_Count.properFlags = 16;
			pAvatar_Kill_Count.aliasID = 9;
			UInt32 Avatar_Kill_Count_defval;
			UInt32.TryParse("0", out Avatar_Kill_Count_defval);
			pAvatar_Kill_Count.defaultVal = Avatar_Kill_Count_defval;
			pAvatarModule.propertys["Kill_Count"] = pAvatar_Kill_Count; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_Kill_Count.aliasID] = pAvatar_Kill_Count;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(Kill_Count / 48006).");

			Property pAvatar_MP = new Property();
			pAvatar_MP.name = "MP";
			pAvatar_MP.properUtype = 47003;
			pAvatar_MP.properFlags = 4;
			pAvatar_MP.aliasID = 10;
			Int32 Avatar_MP_defval;
			Int32.TryParse("0", out Avatar_MP_defval);
			pAvatar_MP.defaultVal = Avatar_MP_defval;
			pAvatarModule.propertys["MP"] = pAvatar_MP; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_MP.aliasID] = pAvatar_MP;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(MP / 47003).");

			Property pAvatar_MP_Max = new Property();
			pAvatar_MP_Max.name = "MP_Max";
			pAvatar_MP_Max.properUtype = 47004;
			pAvatar_MP_Max.properFlags = 4;
			pAvatar_MP_Max.aliasID = 11;
			Int32 Avatar_MP_Max_defval;
			Int32.TryParse("0", out Avatar_MP_Max_defval);
			pAvatar_MP_Max.defaultVal = Avatar_MP_Max_defval;
			pAvatarModule.propertys["MP_Max"] = pAvatar_MP_Max; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_MP_Max.aliasID] = pAvatar_MP_Max;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(MP_Max / 47004).");

			Property pAvatar_Rank = new Property();
			pAvatar_Rank.name = "Rank";
			pAvatar_Rank.properUtype = 48003;
			pAvatar_Rank.properFlags = 16;
			pAvatar_Rank.aliasID = 12;
			UInt32 Avatar_Rank_defval;
			UInt32.TryParse("0", out Avatar_Rank_defval);
			pAvatar_Rank.defaultVal = Avatar_Rank_defval;
			pAvatarModule.propertys["Rank"] = pAvatar_Rank; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_Rank.aliasID] = pAvatar_Rank;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(Rank / 48003).");

			Property pAvatar_Round = new Property();
			pAvatar_Round.name = "Round";
			pAvatar_Round.properUtype = 48001;
			pAvatar_Round.properFlags = 16;
			pAvatar_Round.aliasID = 13;
			Int32 Avatar_Round_defval;
			Int32.TryParse("0", out Avatar_Round_defval);
			pAvatar_Round.defaultVal = Avatar_Round_defval;
			pAvatarModule.propertys["Round"] = pAvatar_Round; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_Round.aliasID] = pAvatar_Round;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(Round / 48001).");

			Property pAvatar_Round_Max = new Property();
			pAvatar_Round_Max.name = "Round_Max";
			pAvatar_Round_Max.properUtype = 48002;
			pAvatar_Round_Max.properFlags = 16;
			pAvatar_Round_Max.aliasID = 14;
			Int32 Avatar_Round_Max_defval;
			Int32.TryParse("0", out Avatar_Round_Max_defval);
			pAvatar_Round_Max.defaultVal = Avatar_Round_Max_defval;
			pAvatarModule.propertys["Round_Max"] = pAvatar_Round_Max; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_Round_Max.aliasID] = pAvatar_Round_Max;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(Round_Max / 48002).");

			Property pAvatar_Score = new Property();
			pAvatar_Score.name = "Score";
			pAvatar_Score.properUtype = 48004;
			pAvatar_Score.properFlags = 16;
			pAvatar_Score.aliasID = 15;
			UInt32 Avatar_Score_defval;
			UInt32.TryParse("0", out Avatar_Score_defval);
			pAvatar_Score.defaultVal = Avatar_Score_defval;
			pAvatarModule.propertys["Score"] = pAvatar_Score; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_Score.aliasID] = pAvatar_Score;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(Score / 48004).");

			Property pAvatar_cruiseSpeed = new Property();
			pAvatar_cruiseSpeed.name = "cruiseSpeed";
			pAvatar_cruiseSpeed.properUtype = 12;
			pAvatar_cruiseSpeed.properFlags = 4;
			pAvatar_cruiseSpeed.aliasID = 16;
			UInt16 Avatar_cruiseSpeed_defval;
			UInt16.TryParse("0", out Avatar_cruiseSpeed_defval);
			pAvatar_cruiseSpeed.defaultVal = Avatar_cruiseSpeed_defval;
			pAvatarModule.propertys["cruiseSpeed"] = pAvatar_cruiseSpeed; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_cruiseSpeed.aliasID] = pAvatar_cruiseSpeed;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(cruiseSpeed / 12).");

			Property pAvatar_level = new Property();
			pAvatar_level.name = "level";
			pAvatar_level.properUtype = 41002;
			pAvatar_level.properFlags = 4;
			pAvatar_level.aliasID = 17;
			UInt16 Avatar_level_defval;
			UInt16.TryParse("", out Avatar_level_defval);
			pAvatar_level.defaultVal = Avatar_level_defval;
			pAvatarModule.propertys["level"] = pAvatar_level; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_level.aliasID] = pAvatar_level;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(level / 41002).");

			Property pAvatar_modelID = new Property();
			pAvatar_modelID.name = "modelID";
			pAvatar_modelID.properUtype = 42006;
			pAvatar_modelID.properFlags = 4;
			pAvatar_modelID.aliasID = 18;
			UInt32 Avatar_modelID_defval;
			UInt32.TryParse("0", out Avatar_modelID_defval);
			pAvatar_modelID.defaultVal = Avatar_modelID_defval;
			pAvatarModule.propertys["modelID"] = pAvatar_modelID; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_modelID.aliasID] = pAvatar_modelID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(modelID / 42006).");

			Property pAvatar_modelScale = new Property();
			pAvatar_modelScale.name = "modelScale";
			pAvatar_modelScale.properUtype = 42007;
			pAvatar_modelScale.properFlags = 4;
			pAvatar_modelScale.aliasID = 19;
			Byte Avatar_modelScale_defval;
			Byte.TryParse("30", out Avatar_modelScale_defval);
			pAvatar_modelScale.defaultVal = Avatar_modelScale_defval;
			pAvatarModule.propertys["modelScale"] = pAvatar_modelScale; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_modelScale.aliasID] = pAvatar_modelScale;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(modelScale / 42007).");

			Property pAvatar_moveSpeed = new Property();
			pAvatar_moveSpeed.name = "moveSpeed";
			pAvatar_moveSpeed.properUtype = 11;
			pAvatar_moveSpeed.properFlags = 4;
			pAvatar_moveSpeed.aliasID = 20;
			UInt16 Avatar_moveSpeed_defval;
			UInt16.TryParse("50", out Avatar_moveSpeed_defval);
			pAvatar_moveSpeed.defaultVal = Avatar_moveSpeed_defval;
			pAvatarModule.propertys["moveSpeed"] = pAvatar_moveSpeed; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_moveSpeed.aliasID] = pAvatar_moveSpeed;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(moveSpeed / 11).");

			Property pAvatar_name = new Property();
			pAvatar_name.name = "name";
			pAvatar_name.properUtype = 42003;
			pAvatar_name.properFlags = 4;
			pAvatar_name.aliasID = 21;
			string Avatar_name_defval = "";
			pAvatar_name.defaultVal = Avatar_name_defval;
			pAvatarModule.propertys["name"] = pAvatar_name; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_name.aliasID] = pAvatar_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(name / 42003).");

			Property pAvatar_spaceUType = new Property();
			pAvatar_spaceUType.name = "spaceUType";
			pAvatar_spaceUType.properUtype = 42008;
			pAvatar_spaceUType.properFlags = 8;
			pAvatar_spaceUType.aliasID = 22;
			UInt32 Avatar_spaceUType_defval;
			UInt32.TryParse("", out Avatar_spaceUType_defval);
			pAvatar_spaceUType.defaultVal = Avatar_spaceUType_defval;
			pAvatarModule.propertys["spaceUType"] = pAvatar_spaceUType; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_spaceUType.aliasID] = pAvatar_spaceUType;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(spaceUType / 42008).");

			Property pAvatar_state = new Property();
			pAvatar_state.name = "state";
			pAvatar_state.properUtype = 44006;
			pAvatar_state.properFlags = 4;
			pAvatar_state.aliasID = 23;
			SByte Avatar_state_defval;
			SByte.TryParse("0", out Avatar_state_defval);
			pAvatar_state.defaultVal = Avatar_state_defval;
			pAvatarModule.propertys["state"] = pAvatar_state; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_state.aliasID] = pAvatar_state;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(state / 44006).");

			Property pAvatar_uid = new Property();
			pAvatar_uid.name = "uid";
			pAvatar_uid.properUtype = 42004;
			pAvatar_uid.properFlags = 4;
			pAvatar_uid.aliasID = 24;
			UInt32 Avatar_uid_defval;
			UInt32.TryParse("0", out Avatar_uid_defval);
			pAvatar_uid.defaultVal = Avatar_uid_defval;
			pAvatarModule.propertys["uid"] = pAvatar_uid; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_uid.aliasID] = pAvatar_uid;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(uid / 42004).");

			Property pAvatar_utype = new Property();
			pAvatar_utype.name = "utype";
			pAvatar_utype.properUtype = 42005;
			pAvatar_utype.properFlags = 4;
			pAvatar_utype.aliasID = 25;
			UInt32 Avatar_utype_defval;
			UInt32.TryParse("0", out Avatar_utype_defval);
			pAvatar_utype.defaultVal = Avatar_utype_defval;
			pAvatarModule.propertys["utype"] = pAvatar_utype; 

			pAvatarModule.usePropertyDescrAlias = true;
			pAvatarModule.idpropertys[(UInt16)pAvatar_utype.aliasID] = pAvatar_utype;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), property(utype / 42005).");

			List<DATATYPE_BASE> pAvatar_canUseWeaponResult_args = new List<DATATYPE_BASE>();
			pAvatar_canUseWeaponResult_args.Add(EntityDef.id2datatypes[3]);
			pAvatar_canUseWeaponResult_args.Add(EntityDef.id2datatypes[2]);

			Method pAvatar_canUseWeaponResult = new Method();
			pAvatar_canUseWeaponResult.name = "canUseWeaponResult";
			pAvatar_canUseWeaponResult.methodUtype = 61003;
			pAvatar_canUseWeaponResult.aliasID = 1;
			pAvatar_canUseWeaponResult.args = pAvatar_canUseWeaponResult_args;

			pAvatarModule.methods["canUseWeaponResult"] = pAvatar_canUseWeaponResult; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_canUseWeaponResult.aliasID] = pAvatar_canUseWeaponResult;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(canUseWeaponResult / 61003).");

			List<DATATYPE_BASE> pAvatar_onJump_args = new List<DATATYPE_BASE>();

			Method pAvatar_onJump = new Method();
			pAvatar_onJump.name = "onJump";
			pAvatar_onJump.methodUtype = 17;
			pAvatar_onJump.aliasID = 2;
			pAvatar_onJump.args = pAvatar_onJump_args;

			pAvatarModule.methods["onJump"] = pAvatar_onJump; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_onJump.aliasID] = pAvatar_onJump;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(onJump / 17).");

			List<DATATYPE_BASE> pAvatar_recvDamage_args = new List<DATATYPE_BASE>();
			pAvatar_recvDamage_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_recvDamage_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_recvDamage_args.Add(EntityDef.id2datatypes[8]);
			pAvatar_recvDamage_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_recvDamage = new Method();
			pAvatar_recvDamage.name = "recvDamage";
			pAvatar_recvDamage.methodUtype = 21;
			pAvatar_recvDamage.aliasID = 3;
			pAvatar_recvDamage.args = pAvatar_recvDamage_args;

			pAvatarModule.methods["recvDamage"] = pAvatar_recvDamage; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_recvDamage.aliasID] = pAvatar_recvDamage;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(recvDamage / 21).");

			List<DATATYPE_BASE> pAvatar_recvPropEffect_args = new List<DATATYPE_BASE>();
			pAvatar_recvPropEffect_args.Add(EntityDef.id2datatypes[4]);
			pAvatar_recvPropEffect_args.Add(EntityDef.id2datatypes[8]);

			Method pAvatar_recvPropEffect = new Method();
			pAvatar_recvPropEffect.name = "recvPropEffect";
			pAvatar_recvPropEffect.methodUtype = 22;
			pAvatar_recvPropEffect.aliasID = 4;
			pAvatar_recvPropEffect.args = pAvatar_recvPropEffect_args;

			pAvatarModule.methods["recvPropEffect"] = pAvatar_recvPropEffect; 
			pAvatarModule.useMethodDescrAlias = true;
			pAvatarModule.idmethods[(UInt16)pAvatar_recvPropEffect.aliasID] = pAvatar_recvPropEffect;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(recvPropEffect / 22).");

			List<DATATYPE_BASE> pAvatar_transAvatar_args = new List<DATATYPE_BASE>();

			Method pAvatar_transAvatar = new Method();
			pAvatar_transAvatar.name = "transAvatar";
			pAvatar_transAvatar.methodUtype = 41003;
			pAvatar_transAvatar.aliasID = -1;
			pAvatar_transAvatar.args = pAvatar_transAvatar_args;

			pAvatarModule.methods["transAvatar"] = pAvatar_transAvatar; 
			pAvatarModule.base_methods["transAvatar"] = pAvatar_transAvatar;

			pAvatarModule.idbase_methods[pAvatar_transAvatar.methodUtype] = pAvatar_transAvatar;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(transAvatar / 41003).");

			List<DATATYPE_BASE> pAvatar_jump_args = new List<DATATYPE_BASE>();

			Method pAvatar_jump = new Method();
			pAvatar_jump.name = "jump";
			pAvatar_jump.methodUtype = 15;
			pAvatar_jump.aliasID = -1;
			pAvatar_jump.args = pAvatar_jump_args;

			pAvatarModule.methods["jump"] = pAvatar_jump; 
			pAvatarModule.cell_methods["jump"] = pAvatar_jump;

			pAvatarModule.idcell_methods[pAvatar_jump.methodUtype] = pAvatar_jump;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(jump / 15).");

			List<DATATYPE_BASE> pAvatar_relive_args = new List<DATATYPE_BASE>();
			pAvatar_relive_args.Add(EntityDef.id2datatypes[2]);

			Method pAvatar_relive = new Method();
			pAvatar_relive.name = "relive";
			pAvatar_relive.methodUtype = 14;
			pAvatar_relive.aliasID = -1;
			pAvatar_relive.args = pAvatar_relive_args;

			pAvatarModule.methods["relive"] = pAvatar_relive; 
			pAvatarModule.cell_methods["relive"] = pAvatar_relive;

			pAvatarModule.idcell_methods[pAvatar_relive.methodUtype] = pAvatar_relive;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(relive / 14).");

			List<DATATYPE_BASE> pAvatar_reqUseWeapon_args = new List<DATATYPE_BASE>();
			pAvatar_reqUseWeapon_args.Add(EntityDef.id2datatypes[16]);
			pAvatar_reqUseWeapon_args.Add(EntityDef.id2datatypes[16]);
			pAvatar_reqUseWeapon_args.Add(EntityDef.id2datatypes[16]);
			pAvatar_reqUseWeapon_args.Add(EntityDef.id2datatypes[4]);

			Method pAvatar_reqUseWeapon = new Method();
			pAvatar_reqUseWeapon.name = "reqUseWeapon";
			pAvatar_reqUseWeapon.methodUtype = 61001;
			pAvatar_reqUseWeapon.aliasID = -1;
			pAvatar_reqUseWeapon.args = pAvatar_reqUseWeapon_args;

			pAvatarModule.methods["reqUseWeapon"] = pAvatar_reqUseWeapon; 
			pAvatarModule.cell_methods["reqUseWeapon"] = pAvatar_reqUseWeapon;

			pAvatarModule.idcell_methods[pAvatar_reqUseWeapon.methodUtype] = pAvatar_reqUseWeapon;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(reqUseWeapon / 61001).");

			List<DATATYPE_BASE> pAvatar_setCruiseSpeed_args = new List<DATATYPE_BASE>();
			pAvatar_setCruiseSpeed_args.Add(EntityDef.id2datatypes[3]);

			Method pAvatar_setCruiseSpeed = new Method();
			pAvatar_setCruiseSpeed.name = "setCruiseSpeed";
			pAvatar_setCruiseSpeed.methodUtype = 18;
			pAvatar_setCruiseSpeed.aliasID = -1;
			pAvatar_setCruiseSpeed.args = pAvatar_setCruiseSpeed_args;

			pAvatarModule.methods["setCruiseSpeed"] = pAvatar_setCruiseSpeed; 
			pAvatarModule.cell_methods["setCruiseSpeed"] = pAvatar_setCruiseSpeed;

			pAvatarModule.idcell_methods[pAvatar_setCruiseSpeed.methodUtype] = pAvatar_setCruiseSpeed;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Avatar), method(setCruiseSpeed / 18).");

			ScriptModule pSupplyBoxModule = new ScriptModule("SupplyBox");
			EntityDef.moduledefs["SupplyBox"] = pSupplyBoxModule;
			EntityDef.idmoduledefs[5] = pSupplyBoxModule;

			Property pSupplyBox_position = new Property();
			pSupplyBox_position.name = "position";
			pSupplyBox_position.properUtype = 40000;
			pSupplyBox_position.properFlags = 4;
			pSupplyBox_position.aliasID = 1;
			Vector3 SupplyBox_position_defval = new Vector3();
			pSupplyBox_position.defaultVal = SupplyBox_position_defval;
			pSupplyBoxModule.propertys["position"] = pSupplyBox_position; 

			pSupplyBoxModule.usePropertyDescrAlias = true;
			pSupplyBoxModule.idpropertys[(UInt16)pSupplyBox_position.aliasID] = pSupplyBox_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(SupplyBox), property(position / 40000).");

			Property pSupplyBox_direction = new Property();
			pSupplyBox_direction.name = "direction";
			pSupplyBox_direction.properUtype = 40001;
			pSupplyBox_direction.properFlags = 4;
			pSupplyBox_direction.aliasID = 2;
			Vector3 SupplyBox_direction_defval = new Vector3();
			pSupplyBox_direction.defaultVal = SupplyBox_direction_defval;
			pSupplyBoxModule.propertys["direction"] = pSupplyBox_direction; 

			pSupplyBoxModule.usePropertyDescrAlias = true;
			pSupplyBoxModule.idpropertys[(UInt16)pSupplyBox_direction.aliasID] = pSupplyBox_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(SupplyBox), property(direction / 40001).");

			Property pSupplyBox_spaceID = new Property();
			pSupplyBox_spaceID.name = "spaceID";
			pSupplyBox_spaceID.properUtype = 40002;
			pSupplyBox_spaceID.properFlags = 16;
			pSupplyBox_spaceID.aliasID = 3;
			UInt32 SupplyBox_spaceID_defval;
			UInt32.TryParse("", out SupplyBox_spaceID_defval);
			pSupplyBox_spaceID.defaultVal = SupplyBox_spaceID_defval;
			pSupplyBoxModule.propertys["spaceID"] = pSupplyBox_spaceID; 

			pSupplyBoxModule.usePropertyDescrAlias = true;
			pSupplyBoxModule.idpropertys[(UInt16)pSupplyBox_spaceID.aliasID] = pSupplyBox_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(SupplyBox), property(spaceID / 40002).");

			Property pSupplyBox_modelID = new Property();
			pSupplyBox_modelID.name = "modelID";
			pSupplyBox_modelID.properUtype = 42006;
			pSupplyBox_modelID.properFlags = 4;
			pSupplyBox_modelID.aliasID = 4;
			UInt32 SupplyBox_modelID_defval;
			UInt32.TryParse("0", out SupplyBox_modelID_defval);
			pSupplyBox_modelID.defaultVal = SupplyBox_modelID_defval;
			pSupplyBoxModule.propertys["modelID"] = pSupplyBox_modelID; 

			pSupplyBoxModule.usePropertyDescrAlias = true;
			pSupplyBoxModule.idpropertys[(UInt16)pSupplyBox_modelID.aliasID] = pSupplyBox_modelID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(SupplyBox), property(modelID / 42006).");

			Property pSupplyBox_modelScale = new Property();
			pSupplyBox_modelScale.name = "modelScale";
			pSupplyBox_modelScale.properUtype = 42007;
			pSupplyBox_modelScale.properFlags = 4;
			pSupplyBox_modelScale.aliasID = 5;
			Byte SupplyBox_modelScale_defval;
			Byte.TryParse("30", out SupplyBox_modelScale_defval);
			pSupplyBox_modelScale.defaultVal = SupplyBox_modelScale_defval;
			pSupplyBoxModule.propertys["modelScale"] = pSupplyBox_modelScale; 

			pSupplyBoxModule.usePropertyDescrAlias = true;
			pSupplyBoxModule.idpropertys[(UInt16)pSupplyBox_modelScale.aliasID] = pSupplyBox_modelScale;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(SupplyBox), property(modelScale / 42007).");

			Property pSupplyBox_name = new Property();
			pSupplyBox_name.name = "name";
			pSupplyBox_name.properUtype = 42003;
			pSupplyBox_name.properFlags = 4;
			pSupplyBox_name.aliasID = 6;
			string SupplyBox_name_defval = "";
			pSupplyBox_name.defaultVal = SupplyBox_name_defval;
			pSupplyBoxModule.propertys["name"] = pSupplyBox_name; 

			pSupplyBoxModule.usePropertyDescrAlias = true;
			pSupplyBoxModule.idpropertys[(UInt16)pSupplyBox_name.aliasID] = pSupplyBox_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(SupplyBox), property(name / 42003).");

			Property pSupplyBox_spaceUType = new Property();
			pSupplyBox_spaceUType.name = "spaceUType";
			pSupplyBox_spaceUType.properUtype = 42008;
			pSupplyBox_spaceUType.properFlags = 8;
			pSupplyBox_spaceUType.aliasID = 7;
			UInt32 SupplyBox_spaceUType_defval;
			UInt32.TryParse("", out SupplyBox_spaceUType_defval);
			pSupplyBox_spaceUType.defaultVal = SupplyBox_spaceUType_defval;
			pSupplyBoxModule.propertys["spaceUType"] = pSupplyBox_spaceUType; 

			pSupplyBoxModule.usePropertyDescrAlias = true;
			pSupplyBoxModule.idpropertys[(UInt16)pSupplyBox_spaceUType.aliasID] = pSupplyBox_spaceUType;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(SupplyBox), property(spaceUType / 42008).");

			Property pSupplyBox_uid = new Property();
			pSupplyBox_uid.name = "uid";
			pSupplyBox_uid.properUtype = 42004;
			pSupplyBox_uid.properFlags = 4;
			pSupplyBox_uid.aliasID = 8;
			UInt32 SupplyBox_uid_defval;
			UInt32.TryParse("0", out SupplyBox_uid_defval);
			pSupplyBox_uid.defaultVal = SupplyBox_uid_defval;
			pSupplyBoxModule.propertys["uid"] = pSupplyBox_uid; 

			pSupplyBoxModule.usePropertyDescrAlias = true;
			pSupplyBoxModule.idpropertys[(UInt16)pSupplyBox_uid.aliasID] = pSupplyBox_uid;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(SupplyBox), property(uid / 42004).");

			Property pSupplyBox_utype = new Property();
			pSupplyBox_utype.name = "utype";
			pSupplyBox_utype.properUtype = 42005;
			pSupplyBox_utype.properFlags = 4;
			pSupplyBox_utype.aliasID = 9;
			UInt32 SupplyBox_utype_defval;
			UInt32.TryParse("0", out SupplyBox_utype_defval);
			pSupplyBox_utype.defaultVal = SupplyBox_utype_defval;
			pSupplyBoxModule.propertys["utype"] = pSupplyBox_utype; 

			pSupplyBoxModule.usePropertyDescrAlias = true;
			pSupplyBoxModule.idpropertys[(UInt16)pSupplyBox_utype.aliasID] = pSupplyBox_utype;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(SupplyBox), property(utype / 42005).");

			List<DATATYPE_BASE> pSupplyBox_onSupplyBoxDestroy_args = new List<DATATYPE_BASE>();
			pSupplyBox_onSupplyBoxDestroy_args.Add(EntityDef.id2datatypes[8]);
			pSupplyBox_onSupplyBoxDestroy_args.Add(EntityDef.id2datatypes[3]);

			Method pSupplyBox_onSupplyBoxDestroy = new Method();
			pSupplyBox_onSupplyBoxDestroy.name = "onSupplyBoxDestroy";
			pSupplyBox_onSupplyBoxDestroy.methodUtype = 11005;
			pSupplyBox_onSupplyBoxDestroy.aliasID = 1;
			pSupplyBox_onSupplyBoxDestroy.args = pSupplyBox_onSupplyBoxDestroy_args;

			pSupplyBoxModule.methods["onSupplyBoxDestroy"] = pSupplyBox_onSupplyBoxDestroy; 
			pSupplyBoxModule.useMethodDescrAlias = true;
			pSupplyBoxModule.idmethods[(UInt16)pSupplyBox_onSupplyBoxDestroy.aliasID] = pSupplyBox_onSupplyBoxDestroy;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(SupplyBox), method(onSupplyBoxDestroy / 11005).");

			ScriptModule pMineModule = new ScriptModule("Mine");
			EntityDef.moduledefs["Mine"] = pMineModule;
			EntityDef.idmoduledefs[6] = pMineModule;

			Property pMine_position = new Property();
			pMine_position.name = "position";
			pMine_position.properUtype = 40000;
			pMine_position.properFlags = 4;
			pMine_position.aliasID = 1;
			Vector3 Mine_position_defval = new Vector3();
			pMine_position.defaultVal = Mine_position_defval;
			pMineModule.propertys["position"] = pMine_position; 

			pMineModule.usePropertyDescrAlias = true;
			pMineModule.idpropertys[(UInt16)pMine_position.aliasID] = pMine_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Mine), property(position / 40000).");

			Property pMine_direction = new Property();
			pMine_direction.name = "direction";
			pMine_direction.properUtype = 40001;
			pMine_direction.properFlags = 4;
			pMine_direction.aliasID = 2;
			Vector3 Mine_direction_defval = new Vector3();
			pMine_direction.defaultVal = Mine_direction_defval;
			pMineModule.propertys["direction"] = pMine_direction; 

			pMineModule.usePropertyDescrAlias = true;
			pMineModule.idpropertys[(UInt16)pMine_direction.aliasID] = pMine_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Mine), property(direction / 40001).");

			Property pMine_spaceID = new Property();
			pMine_spaceID.name = "spaceID";
			pMine_spaceID.properUtype = 40002;
			pMine_spaceID.properFlags = 16;
			pMine_spaceID.aliasID = 3;
			UInt32 Mine_spaceID_defval;
			UInt32.TryParse("", out Mine_spaceID_defval);
			pMine_spaceID.defaultVal = Mine_spaceID_defval;
			pMineModule.propertys["spaceID"] = pMine_spaceID; 

			pMineModule.usePropertyDescrAlias = true;
			pMineModule.idpropertys[(UInt16)pMine_spaceID.aliasID] = pMine_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Mine), property(spaceID / 40002).");

			Property pMine_modelID = new Property();
			pMine_modelID.name = "modelID";
			pMine_modelID.properUtype = 42006;
			pMine_modelID.properFlags = 4;
			pMine_modelID.aliasID = 4;
			UInt32 Mine_modelID_defval;
			UInt32.TryParse("0", out Mine_modelID_defval);
			pMine_modelID.defaultVal = Mine_modelID_defval;
			pMineModule.propertys["modelID"] = pMine_modelID; 

			pMineModule.usePropertyDescrAlias = true;
			pMineModule.idpropertys[(UInt16)pMine_modelID.aliasID] = pMine_modelID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Mine), property(modelID / 42006).");

			Property pMine_modelScale = new Property();
			pMine_modelScale.name = "modelScale";
			pMine_modelScale.properUtype = 42007;
			pMine_modelScale.properFlags = 4;
			pMine_modelScale.aliasID = 5;
			Byte Mine_modelScale_defval;
			Byte.TryParse("30", out Mine_modelScale_defval);
			pMine_modelScale.defaultVal = Mine_modelScale_defval;
			pMineModule.propertys["modelScale"] = pMine_modelScale; 

			pMineModule.usePropertyDescrAlias = true;
			pMineModule.idpropertys[(UInt16)pMine_modelScale.aliasID] = pMine_modelScale;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Mine), property(modelScale / 42007).");

			Property pMine_name = new Property();
			pMine_name.name = "name";
			pMine_name.properUtype = 42003;
			pMine_name.properFlags = 4;
			pMine_name.aliasID = 6;
			string Mine_name_defval = "";
			pMine_name.defaultVal = Mine_name_defval;
			pMineModule.propertys["name"] = pMine_name; 

			pMineModule.usePropertyDescrAlias = true;
			pMineModule.idpropertys[(UInt16)pMine_name.aliasID] = pMine_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Mine), property(name / 42003).");

			Property pMine_spaceUType = new Property();
			pMine_spaceUType.name = "spaceUType";
			pMine_spaceUType.properUtype = 42008;
			pMine_spaceUType.properFlags = 8;
			pMine_spaceUType.aliasID = 7;
			UInt32 Mine_spaceUType_defval;
			UInt32.TryParse("", out Mine_spaceUType_defval);
			pMine_spaceUType.defaultVal = Mine_spaceUType_defval;
			pMineModule.propertys["spaceUType"] = pMine_spaceUType; 

			pMineModule.usePropertyDescrAlias = true;
			pMineModule.idpropertys[(UInt16)pMine_spaceUType.aliasID] = pMine_spaceUType;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Mine), property(spaceUType / 42008).");

			Property pMine_uid = new Property();
			pMine_uid.name = "uid";
			pMine_uid.properUtype = 42004;
			pMine_uid.properFlags = 4;
			pMine_uid.aliasID = 8;
			UInt32 Mine_uid_defval;
			UInt32.TryParse("0", out Mine_uid_defval);
			pMine_uid.defaultVal = Mine_uid_defval;
			pMineModule.propertys["uid"] = pMine_uid; 

			pMineModule.usePropertyDescrAlias = true;
			pMineModule.idpropertys[(UInt16)pMine_uid.aliasID] = pMine_uid;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Mine), property(uid / 42004).");

			Property pMine_utype = new Property();
			pMine_utype.name = "utype";
			pMine_utype.properUtype = 42005;
			pMine_utype.properFlags = 4;
			pMine_utype.aliasID = 9;
			UInt32 Mine_utype_defval;
			UInt32.TryParse("0", out Mine_utype_defval);
			pMine_utype.defaultVal = Mine_utype_defval;
			pMineModule.propertys["utype"] = pMine_utype; 

			pMineModule.usePropertyDescrAlias = true;
			pMineModule.idpropertys[(UInt16)pMine_utype.aliasID] = pMine_utype;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Mine), property(utype / 42005).");

			List<DATATYPE_BASE> pMine_onMineDestroy_args = new List<DATATYPE_BASE>();
			pMine_onMineDestroy_args.Add(EntityDef.id2datatypes[8]);
			pMine_onMineDestroy_args.Add(EntityDef.id2datatypes[3]);

			Method pMine_onMineDestroy = new Method();
			pMine_onMineDestroy.name = "onMineDestroy";
			pMine_onMineDestroy.methodUtype = 61005;
			pMine_onMineDestroy.aliasID = 1;
			pMine_onMineDestroy.args = pMine_onMineDestroy_args;

			pMineModule.methods["onMineDestroy"] = pMine_onMineDestroy; 
			pMineModule.useMethodDescrAlias = true;
			pMineModule.idmethods[(UInt16)pMine_onMineDestroy.aliasID] = pMine_onMineDestroy;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Mine), method(onMineDestroy / 61005).");

			ScriptModule pWeaponModule = new ScriptModule("Weapon");
			EntityDef.moduledefs["Weapon"] = pWeaponModule;
			EntityDef.idmoduledefs[7] = pWeaponModule;

			Property pWeapon_position = new Property();
			pWeapon_position.name = "position";
			pWeapon_position.properUtype = 40000;
			pWeapon_position.properFlags = 4;
			pWeapon_position.aliasID = 1;
			Vector3 Weapon_position_defval = new Vector3();
			pWeapon_position.defaultVal = Weapon_position_defval;
			pWeaponModule.propertys["position"] = pWeapon_position; 

			pWeaponModule.usePropertyDescrAlias = true;
			pWeaponModule.idpropertys[(UInt16)pWeapon_position.aliasID] = pWeapon_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Weapon), property(position / 40000).");

			Property pWeapon_direction = new Property();
			pWeapon_direction.name = "direction";
			pWeapon_direction.properUtype = 40001;
			pWeapon_direction.properFlags = 4;
			pWeapon_direction.aliasID = 2;
			Vector3 Weapon_direction_defval = new Vector3();
			pWeapon_direction.defaultVal = Weapon_direction_defval;
			pWeaponModule.propertys["direction"] = pWeapon_direction; 

			pWeaponModule.usePropertyDescrAlias = true;
			pWeaponModule.idpropertys[(UInt16)pWeapon_direction.aliasID] = pWeapon_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Weapon), property(direction / 40001).");

			Property pWeapon_spaceID = new Property();
			pWeapon_spaceID.name = "spaceID";
			pWeapon_spaceID.properUtype = 40002;
			pWeapon_spaceID.properFlags = 16;
			pWeapon_spaceID.aliasID = 3;
			UInt32 Weapon_spaceID_defval;
			UInt32.TryParse("", out Weapon_spaceID_defval);
			pWeapon_spaceID.defaultVal = Weapon_spaceID_defval;
			pWeaponModule.propertys["spaceID"] = pWeapon_spaceID; 

			pWeaponModule.usePropertyDescrAlias = true;
			pWeaponModule.idpropertys[(UInt16)pWeapon_spaceID.aliasID] = pWeapon_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Weapon), property(spaceID / 40002).");

			Property pWeapon_CD = new Property();
			pWeapon_CD.name = "CD";
			pWeapon_CD.properUtype = 51003;
			pWeapon_CD.properFlags = 8;
			pWeapon_CD.aliasID = 4;
			UInt16 Weapon_CD_defval;
			UInt16.TryParse("0", out Weapon_CD_defval);
			pWeapon_CD.defaultVal = Weapon_CD_defval;
			pWeaponModule.propertys["CD"] = pWeapon_CD; 

			pWeaponModule.usePropertyDescrAlias = true;
			pWeaponModule.idpropertys[(UInt16)pWeapon_CD.aliasID] = pWeapon_CD;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Weapon), property(CD / 51003).");

			Property pWeapon_attackerID = new Property();
			pWeapon_attackerID.name = "attackerID";
			pWeapon_attackerID.properUtype = 51001;
			pWeapon_attackerID.properFlags = 8;
			pWeapon_attackerID.aliasID = 5;
			UInt16 Weapon_attackerID_defval;
			UInt16.TryParse("0", out Weapon_attackerID_defval);
			pWeapon_attackerID.defaultVal = Weapon_attackerID_defval;
			pWeaponModule.propertys["attackerID"] = pWeapon_attackerID; 

			pWeaponModule.usePropertyDescrAlias = true;
			pWeaponModule.idpropertys[(UInt16)pWeapon_attackerID.aliasID] = pWeapon_attackerID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Weapon), property(attackerID / 51001).");

			Property pWeapon_cruiseSpeed = new Property();
			pWeapon_cruiseSpeed.name = "cruiseSpeed";
			pWeapon_cruiseSpeed.properUtype = 23;
			pWeapon_cruiseSpeed.properFlags = 4;
			pWeapon_cruiseSpeed.aliasID = 6;
			UInt16 Weapon_cruiseSpeed_defval;
			UInt16.TryParse("0", out Weapon_cruiseSpeed_defval);
			pWeapon_cruiseSpeed.defaultVal = Weapon_cruiseSpeed_defval;
			pWeaponModule.propertys["cruiseSpeed"] = pWeapon_cruiseSpeed; 

			pWeaponModule.usePropertyDescrAlias = true;
			pWeaponModule.idpropertys[(UInt16)pWeapon_cruiseSpeed.aliasID] = pWeapon_cruiseSpeed;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Weapon), property(cruiseSpeed / 23).");

			Property pWeapon_destForward = new Property();
			pWeapon_destForward.name = "destForward";
			pWeapon_destForward.properUtype = 51004;
			pWeapon_destForward.properFlags = 8;
			pWeapon_destForward.aliasID = 7;
			Vector3 Weapon_destForward_defval = new Vector3();
			pWeapon_destForward.defaultVal = Weapon_destForward_defval;
			pWeaponModule.propertys["destForward"] = pWeapon_destForward; 

			pWeaponModule.usePropertyDescrAlias = true;
			pWeaponModule.idpropertys[(UInt16)pWeapon_destForward.aliasID] = pWeapon_destForward;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Weapon), property(destForward / 51004).");

			Property pWeapon_modelID = new Property();
			pWeapon_modelID.name = "modelID";
			pWeapon_modelID.properUtype = 42006;
			pWeapon_modelID.properFlags = 4;
			pWeapon_modelID.aliasID = 8;
			UInt32 Weapon_modelID_defval;
			UInt32.TryParse("0", out Weapon_modelID_defval);
			pWeapon_modelID.defaultVal = Weapon_modelID_defval;
			pWeaponModule.propertys["modelID"] = pWeapon_modelID; 

			pWeaponModule.usePropertyDescrAlias = true;
			pWeaponModule.idpropertys[(UInt16)pWeapon_modelID.aliasID] = pWeapon_modelID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Weapon), property(modelID / 42006).");

			Property pWeapon_modelScale = new Property();
			pWeapon_modelScale.name = "modelScale";
			pWeapon_modelScale.properUtype = 42007;
			pWeapon_modelScale.properFlags = 4;
			pWeapon_modelScale.aliasID = 9;
			Byte Weapon_modelScale_defval;
			Byte.TryParse("30", out Weapon_modelScale_defval);
			pWeapon_modelScale.defaultVal = Weapon_modelScale_defval;
			pWeaponModule.propertys["modelScale"] = pWeapon_modelScale; 

			pWeaponModule.usePropertyDescrAlias = true;
			pWeaponModule.idpropertys[(UInt16)pWeapon_modelScale.aliasID] = pWeapon_modelScale;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Weapon), property(modelScale / 42007).");

			Property pWeapon_moveSpeed = new Property();
			pWeapon_moveSpeed.name = "moveSpeed";
			pWeapon_moveSpeed.properUtype = 22;
			pWeapon_moveSpeed.properFlags = 4;
			pWeapon_moveSpeed.aliasID = 10;
			UInt16 Weapon_moveSpeed_defval;
			UInt16.TryParse("50", out Weapon_moveSpeed_defval);
			pWeapon_moveSpeed.defaultVal = Weapon_moveSpeed_defval;
			pWeaponModule.propertys["moveSpeed"] = pWeapon_moveSpeed; 

			pWeaponModule.usePropertyDescrAlias = true;
			pWeaponModule.idpropertys[(UInt16)pWeapon_moveSpeed.aliasID] = pWeapon_moveSpeed;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Weapon), property(moveSpeed / 22).");

			Property pWeapon_name = new Property();
			pWeapon_name.name = "name";
			pWeapon_name.properUtype = 42003;
			pWeapon_name.properFlags = 4;
			pWeapon_name.aliasID = 11;
			string Weapon_name_defval = "";
			pWeapon_name.defaultVal = Weapon_name_defval;
			pWeaponModule.propertys["name"] = pWeapon_name; 

			pWeaponModule.usePropertyDescrAlias = true;
			pWeaponModule.idpropertys[(UInt16)pWeapon_name.aliasID] = pWeapon_name;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Weapon), property(name / 42003).");

			Property pWeapon_ownerID = new Property();
			pWeapon_ownerID.name = "ownerID";
			pWeapon_ownerID.properUtype = 51002;
			pWeapon_ownerID.properFlags = 8;
			pWeapon_ownerID.aliasID = 12;
			UInt16 Weapon_ownerID_defval;
			UInt16.TryParse("0", out Weapon_ownerID_defval);
			pWeapon_ownerID.defaultVal = Weapon_ownerID_defval;
			pWeaponModule.propertys["ownerID"] = pWeapon_ownerID; 

			pWeaponModule.usePropertyDescrAlias = true;
			pWeaponModule.idpropertys[(UInt16)pWeapon_ownerID.aliasID] = pWeapon_ownerID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Weapon), property(ownerID / 51002).");

			Property pWeapon_spaceUType = new Property();
			pWeapon_spaceUType.name = "spaceUType";
			pWeapon_spaceUType.properUtype = 42008;
			pWeapon_spaceUType.properFlags = 8;
			pWeapon_spaceUType.aliasID = 13;
			UInt32 Weapon_spaceUType_defval;
			UInt32.TryParse("", out Weapon_spaceUType_defval);
			pWeapon_spaceUType.defaultVal = Weapon_spaceUType_defval;
			pWeaponModule.propertys["spaceUType"] = pWeapon_spaceUType; 

			pWeaponModule.usePropertyDescrAlias = true;
			pWeaponModule.idpropertys[(UInt16)pWeapon_spaceUType.aliasID] = pWeapon_spaceUType;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Weapon), property(spaceUType / 42008).");

			Property pWeapon_state = new Property();
			pWeapon_state.name = "state";
			pWeapon_state.properUtype = 44006;
			pWeapon_state.properFlags = 4;
			pWeapon_state.aliasID = 14;
			SByte Weapon_state_defval;
			SByte.TryParse("0", out Weapon_state_defval);
			pWeapon_state.defaultVal = Weapon_state_defval;
			pWeaponModule.propertys["state"] = pWeapon_state; 

			pWeaponModule.usePropertyDescrAlias = true;
			pWeaponModule.idpropertys[(UInt16)pWeapon_state.aliasID] = pWeapon_state;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Weapon), property(state / 44006).");

			Property pWeapon_uid = new Property();
			pWeapon_uid.name = "uid";
			pWeapon_uid.properUtype = 42004;
			pWeapon_uid.properFlags = 4;
			pWeapon_uid.aliasID = 15;
			UInt32 Weapon_uid_defval;
			UInt32.TryParse("0", out Weapon_uid_defval);
			pWeapon_uid.defaultVal = Weapon_uid_defval;
			pWeaponModule.propertys["uid"] = pWeapon_uid; 

			pWeaponModule.usePropertyDescrAlias = true;
			pWeaponModule.idpropertys[(UInt16)pWeapon_uid.aliasID] = pWeapon_uid;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Weapon), property(uid / 42004).");

			Property pWeapon_utype = new Property();
			pWeapon_utype.name = "utype";
			pWeapon_utype.properUtype = 42005;
			pWeapon_utype.properFlags = 4;
			pWeapon_utype.aliasID = 16;
			UInt32 Weapon_utype_defval;
			UInt32.TryParse("0", out Weapon_utype_defval);
			pWeapon_utype.defaultVal = Weapon_utype_defval;
			pWeaponModule.propertys["utype"] = pWeapon_utype; 

			pWeaponModule.usePropertyDescrAlias = true;
			pWeaponModule.idpropertys[(UInt16)pWeapon_utype.aliasID] = pWeapon_utype;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Weapon), property(utype / 42005).");

			List<DATATYPE_BASE> pWeapon_onWeaponDestroy_args = new List<DATATYPE_BASE>();
			pWeapon_onWeaponDestroy_args.Add(EntityDef.id2datatypes[3]);

			Method pWeapon_onWeaponDestroy = new Method();
			pWeapon_onWeaponDestroy.name = "onWeaponDestroy";
			pWeapon_onWeaponDestroy.methodUtype = 51005;
			pWeapon_onWeaponDestroy.aliasID = 1;
			pWeapon_onWeaponDestroy.args = pWeapon_onWeaponDestroy_args;

			pWeaponModule.methods["onWeaponDestroy"] = pWeapon_onWeaponDestroy; 
			pWeaponModule.useMethodDescrAlias = true;
			pWeaponModule.idmethods[(UInt16)pWeapon_onWeaponDestroy.aliasID] = pWeapon_onWeaponDestroy;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Weapon), method(onWeaponDestroy / 51005).");

			List<DATATYPE_BASE> pWeapon_setCruiseSpeed_args = new List<DATATYPE_BASE>();
			pWeapon_setCruiseSpeed_args.Add(EntityDef.id2datatypes[3]);

			Method pWeapon_setCruiseSpeed = new Method();
			pWeapon_setCruiseSpeed.name = "setCruiseSpeed";
			pWeapon_setCruiseSpeed.methodUtype = 40;
			pWeapon_setCruiseSpeed.aliasID = -1;
			pWeapon_setCruiseSpeed.args = pWeapon_setCruiseSpeed_args;

			pWeaponModule.methods["setCruiseSpeed"] = pWeapon_setCruiseSpeed; 
			pWeaponModule.cell_methods["setCruiseSpeed"] = pWeapon_setCruiseSpeed;

			pWeaponModule.idcell_methods[pWeapon_setCruiseSpeed.methodUtype] = pWeapon_setCruiseSpeed;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Weapon), method(setCruiseSpeed / 40).");

		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "ENTITY_SUBSTATE";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "UINT16";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "SPACE_KEY";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "PROP_ID";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "ENTITY_STATE";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "ENTITY_FORBIDS";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "UNICODE";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "UID1";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "DIRECTION3D";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 22;
				string typeName = "ENTITY_FORBID_COUNTER";
				DATATYPE_ENTITY_FORBID_COUNTER datatype = new DATATYPE_ENTITY_FORBID_COUNTER();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 23;
				string typeName = "ENTITYID_LIST";
				DATATYPE_ENTITYID_LIST datatype = new DATATYPE_ENTITYID_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 24;
				string typeName = "EXAMPLES";
				DATATYPE_EXAMPLES datatype = new DATATYPE_EXAMPLES();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 25;
				string typeName = "AVATAR_DATA";
				DATATYPE_AVATAR_DATA datatype = new DATATYPE_AVATAR_DATA();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 26;
				string typeName = "AVATAR_INFOS";
				DATATYPE_AVATAR_INFOS datatype = new DATATYPE_AVATAR_INFOS();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 27;
				string typeName = "AVATAR_INFOS_LIST";
				DATATYPE_AVATAR_INFOS_LIST datatype = new DATATYPE_AVATAR_INFOS_LIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 29;
				string typeName = "BAG";
				DATATYPE_BAG datatype = new DATATYPE_BAG();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}