//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8922
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CONF
{
    [System.SerializableAttribute()]
    public class conf_base
    {
        public bool init = false;

        public virtual Dictionary<UInt32, object> ReadOneExcel(string filename)
        {
            return new Dictionary<uint, object>();
        }

    }


}